apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  selector:
    matchLabels:
      app: cart-deployment
  template:
    metadata:
      labels:
        app: cart-deployment
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cart-deployment
              topologyKey: kubernetes.azure.com/agentpool
